// Generated by pansakorn

declare namespace angular.googletagmanager {

    interface Static {
        /**
             * .googletagmanager
             * @param {String} string
             * @param {String} string
             * @return {String}
             */
            googletagmanager(id: string, datalayer?: string);
    }
}

declare module 'angular-googletagmanager' {
    // export default "angularAccounting.Static";
    export default "googletagmanager.Static";

    // export = angularAccounting;
}
